version: '3.8'

services:
  # Backend service (API and core logic)
  nofx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: nofx-trading
    restart: unless-stopped
    ports:
      - "${NOFX_BACKEND_PORT:-8080}:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./decision_logs:/app/decision_logs
      - /etc/localtime:/etc/localtime:ro  # Sync host time
    environment:
      - TZ=${NOFX_TIMEZONE:-Asia/Shanghai}  # Set timezone
    networks:
      - nofx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  nofx-network:
    driver: bridge

